[font]
size = 16

[font.bold]
family = "MesloLGS Nerd Font"

[font.bold_italic]
family = "MesloLGS Nerd Font"

[font.italic]
family = "MesloLGS Nerd Font"

[font.normal]
family = "MesloLGS Nerd Font"
